package com.raoul.walkfoframe.database;

import android.database.sqlite.SQLiteDatabase;

import com.raoul.walkfoframe.dao.FavoriteDao;
import com.raoul.walkfoframe.dao.HonoreesandStarDao;
import com.raoul.walkfoframe.dao.QuestionsDao;
import com.raoul.walkfoframe.dao.QuizzesDao;
import com.raoul.walkfoframe.dao.WOFControlDao;
import com.raoul.walkfoframe.dao.WOFCouponCatDao;
import com.raoul.walkfoframe.dao.WOFCouponsDao;
import com.raoul.walkfoframe.dao.WOFMediaDao;
import com.raoul.walkfoframe.dao.WOFStarsDao;
import com.raoul.walkfoframe.dao.WOF_USERDao;
import com.raoul.walkfoframe.dao.WofhonoreesDao;
import com.raoul.walkfoframe.model.Favorite;
import com.raoul.walkfoframe.model.HonoreesandStar;
import com.raoul.walkfoframe.model.Questions;
import com.raoul.walkfoframe.model.Quizzes;
import com.raoul.walkfoframe.model.WOFControl;
import com.raoul.walkfoframe.model.WOFCouponCat;
import com.raoul.walkfoframe.model.WOFCoupons;
import com.raoul.walkfoframe.model.WOFMedia;
import com.raoul.walkfoframe.model.WOFStars;
import com.raoul.walkfoframe.model.WOF_USER;
import com.raoul.walkfoframe.model.Wofhonorees;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

  private final DaoConfig wofhonoreesDaoConfig;

  private final WofhonoreesDao wofhonoreesDao;
  private final DaoConfig wOFStarsDaoConfig;
  private final DaoConfig wOFMediaDaoConfig;
  private final DaoConfig wOFCouponsDaoConfig;
  private final DaoConfig questionsDaoConfig;
  private final DaoConfig wOFControlDaoConfig;
  private final DaoConfig quizzesDaoConfig;
  private final DaoConfig wOF_USERDaoConfig;

  private final WOFStarsDao wOFStarsDao;
  private final WOFMediaDao wOFMediaDao;
  private final WOFCouponsDao wOFCouponsDao;
  private final QuestionsDao questionsDao;
  private final WOFControlDao wOFControlDao;
  private final QuizzesDao quizzesDao;
  private final WOF_USERDao wOF_USERDao;
  private final DaoConfig favoriteDaoConfig;
  private final FavoriteDao favoriteDao;
  private final DaoConfig wOFCouponCatDaoConfig;

  private final WOFCouponCatDao wOFCouponCatDao;
  private final DaoConfig honoreesandstarDaoConfig;

  private final HonoreesandStarDao honoreesandstarDao;

  public DaoSession(SQLiteDatabase db, IdentityScopeType type,
      Map<Class<? extends AbstractDao<?, ?>>, DaoConfig> daoConfigMap) {
    super(db);
    favoriteDaoConfig = daoConfigMap.get(FavoriteDao.class).clone();
    favoriteDaoConfig.initIdentityScope(type);

    favoriteDao = new FavoriteDao(favoriteDaoConfig, this);

    registerDao(Favorite.class, favoriteDao);
    wofhonoreesDaoConfig = daoConfigMap.get(WofhonoreesDao.class).clone();
    wofhonoreesDaoConfig.initIdentityScope(type);

    wofhonoreesDao = new WofhonoreesDao(wofhonoreesDaoConfig, this);

    registerDao(Wofhonorees.class, wofhonoreesDao);

    wOFStarsDaoConfig = daoConfigMap.get(WOFStarsDao.class).clone();
    wOFStarsDaoConfig.initIdentityScope(type);

    wOFMediaDaoConfig = daoConfigMap.get(WOFMediaDao.class).clone();
    wOFMediaDaoConfig.initIdentityScope(type);

    wOFCouponsDaoConfig = daoConfigMap.get(WOFCouponsDao.class).clone();
    wOFCouponsDaoConfig.initIdentityScope(type);

    questionsDaoConfig = daoConfigMap.get(QuestionsDao.class).clone();
    questionsDaoConfig.initIdentityScope(type);

    wOFControlDaoConfig = daoConfigMap.get(WOFControlDao.class).clone();
    wOFControlDaoConfig.initIdentityScope(type);

    quizzesDaoConfig = daoConfigMap.get(QuizzesDao.class).clone();
    quizzesDaoConfig.initIdentityScope(type);

    wOF_USERDaoConfig = daoConfigMap.get(WOF_USERDao.class).clone();
    wOF_USERDaoConfig.initIdentityScope(type);

    wOFStarsDao = new WOFStarsDao(wOFStarsDaoConfig, this);
    wOFMediaDao = new WOFMediaDao(wOFMediaDaoConfig, this);
    wOFCouponsDao = new WOFCouponsDao(wOFCouponsDaoConfig, this);
    questionsDao = new QuestionsDao(questionsDaoConfig, this);
    wOFControlDao = new WOFControlDao(wOFControlDaoConfig, this);
    quizzesDao = new QuizzesDao(quizzesDaoConfig, this);
    wOF_USERDao = new WOF_USERDao(wOF_USERDaoConfig, this);
    wOFCouponCatDaoConfig = daoConfigMap.get(WOFCouponCatDao.class).clone();
    wOFCouponCatDaoConfig.initIdentityScope(type);
    wOFCouponCatDao = new WOFCouponCatDao(wOFCouponCatDaoConfig, this);
    honoreesandstarDaoConfig = daoConfigMap.get(HonoreesandStarDao.class).clone();
    honoreesandstarDaoConfig.initIdentityScope(type);
    honoreesandstarDao = new HonoreesandStarDao(honoreesandstarDaoConfig, this);
    registerDao(HonoreesandStar.class, honoreesandstarDao);
    registerDao(WOFCouponCat.class, wOFCouponCatDao);
    registerDao(WOFStars.class, wOFStarsDao);
    registerDao(WOFMedia.class, wOFMediaDao);
    registerDao(WOFCoupons.class, wOFCouponsDao);
    registerDao(Questions.class, questionsDao);
    registerDao(WOFControl.class, wOFControlDao);
    registerDao(Quizzes.class, quizzesDao);
    registerDao(WOF_USER.class, wOF_USERDao);

  }

  public void clear() {
    favoriteDaoConfig.getIdentityScope().clear();
    wofhonoreesDaoConfig.getIdentityScope().clear();
    wOFStarsDaoConfig.getIdentityScope().clear();
    wOFMediaDaoConfig.getIdentityScope().clear();
    wOFCouponsDaoConfig.getIdentityScope().clear();
    questionsDaoConfig.getIdentityScope().clear();
    wOFControlDaoConfig.getIdentityScope().clear();
    quizzesDaoConfig.getIdentityScope().clear();
    wOF_USERDaoConfig.getIdentityScope().clear();
    wOFCouponCatDaoConfig.getIdentityScope().clear();
    honoreesandstarDaoConfig.getIdentityScope().clear();
  }

  public WOFCouponCatDao getWOFCouponCatDao() {
    return wOFCouponCatDao;
  }

  public FavoriteDao getFavoriteDao() {
    return favoriteDao;
  }

  public WofhonoreesDao getWofhonoreesDao() {
    return wofhonoreesDao;
  }

  public WOFStarsDao getWOFStarsDao() {
    return wOFStarsDao;
  }

  public WOFMediaDao getWOFMediaDao() {
    return wOFMediaDao;
  }

  public WOFCouponsDao getWOFCouponsDao() {
    return wOFCouponsDao;
  }

  public QuestionsDao getQuestionsDao() {
    return questionsDao;
  }

  public WOFControlDao getWOFControlDao() {
    return wOFControlDao;
  }

  public QuizzesDao getQuizzesDao() {
    return quizzesDao;
  }

  public WOF_USERDao getWOF_USERDao() {
    return wOF_USERDao;
  }

  public HonoreesandStarDao getHonoreesandstarDao() {
    return honoreesandstarDao;
  }
}
