package com.raoul.walkfoframe.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table FAVORITE.
 */
public class Favorite {

  private String honoreeID;
  private String bioThumbnail;
  private String biography;
  private String birthCity;
  private String birthCountry;
  private String birthDate;
  private String createdTimeStamp;
  private String deathCity;
  private String deathState;
  private String education;
  private String ethnicity;
  private String inductionDate;
  private String fullName;
  private String nameFullFirst;
  private String nameFullFirstLetter;
  private String nameFullLast;

  public Wofhonorees getHonorees() {
    return honorees;
  }

  public void setHonorees(Wofhonorees honorees) {
    this.honorees = honorees;
  }

  private Wofhonorees honorees;

  public Favorite() {}

  public Favorite(Wofhonorees honoress) {
    this.honorees = honoress;
    this.honoreeID = String.valueOf(honoress.getHonoreeID());
    this.bioThumbnail = honorees.getBioThumbnail();;
    this.biography = honorees.getBiography();
    this.birthCity = honorees.getBirthCity();
    this.birthCountry = honorees.getBirthCountry();
    this.birthDate = honorees.getBirthDate();
    this.createdTimeStamp = honorees.getCreatedTimeStamp();
    this.deathCity = honorees.getDeathCity();
    this.deathState = honorees.getDeathState();
    this.education = honorees.getEducation();
    this.ethnicity = honorees.getEthnicity();
    this.inductionDate = honorees.getInductionDate();
    this.fullName = honorees.getFullName();
    this.nameFullFirst = honorees.getNameFullFirst();
    this.nameFullFirstLetter = honorees.getNameFullFirstLetter();
    this.nameFullLast = honorees.getNameFullLast();



  }



  public Favorite(String honoreeID, String bioThumbnail, String biography, String birthCity,
      String birthCountry, String birthDate, String createdTimeStamp, String deathCity,
      String deathState, String education, String ethnicity, String inductionDate, String fullName,
      String nameFullFirst, String nameFullFirstLetter, String nameFullLast) {
    this.honoreeID = honoreeID;
    this.bioThumbnail = bioThumbnail;
    this.biography = biography;
    this.birthCity = birthCity;
    this.birthCountry = birthCountry;
    this.birthDate = birthDate;
    this.createdTimeStamp = createdTimeStamp;
    this.deathCity = deathCity;
    this.deathState = deathState;
    this.education = education;
    this.ethnicity = ethnicity;
    this.inductionDate = inductionDate;
    this.fullName = fullName;
    this.nameFullFirst = nameFullFirst;
    this.nameFullFirstLetter = nameFullFirstLetter;
    this.nameFullLast = nameFullLast;
    
  }

  public String getHonoreeID() {
    return honoreeID;
  }

  public void setHonoreeID(String honoreeID) {
    this.honoreeID = honoreeID;
  }

  public String getBioThumbnail() {
    return bioThumbnail;
  }

  public void setBioThumbnail(String bioThumbnail) {
    this.bioThumbnail = bioThumbnail;
  }

  public String getBiography() {
    return biography;
  }

  public void setBiography(String biography) {
    this.biography = biography;
  }

  public String getBirthCity() {
    return birthCity;
  }

  public void setBirthCity(String birthCity) {
    this.birthCity = birthCity;
  }

  public String getBirthCountry() {
    return birthCountry;
  }

  public void setBirthCountry(String birthCountry) {
    this.birthCountry = birthCountry;
  }

  public String getBirthDate() {
    return birthDate;
  }

  public void setBirthDate(String birthDate) {
    this.birthDate = birthDate;
  }

  public String getCreatedTimeStamp() {
    return createdTimeStamp;
  }

  public void setCreatedTimeStamp(String createdTimeStamp) {
    this.createdTimeStamp = createdTimeStamp;
  }

  public String getDeathCity() {
    return deathCity;
  }

  public void setDeathCity(String deathCity) {
    this.deathCity = deathCity;
  }

  public String getDeathState() {
    return deathState;
  }

  public void setDeathState(String deathState) {
    this.deathState = deathState;
  }

  public String getEducation() {
    return education;
  }

  public void setEducation(String education) {
    this.education = education;
  }

  public String getEthnicity() {
    return ethnicity;
  }

  public void setEthnicity(String ethnicity) {
    this.ethnicity = ethnicity;
  }

  public String getInductionDate() {
    return inductionDate;
  }

  public void setInductionDate(String inductionDate) {
    this.inductionDate = inductionDate;
  }

  public String getFullName() {
    return fullName;
  }

  public void setFullName(String fullName) {
    this.fullName = fullName;
  }

  public String getNameFullFirst() {
    return nameFullFirst;
  }

  public void setNameFullFirst(String nameFullFirst) {
    this.nameFullFirst = nameFullFirst;
  }

  public String getNameFullFirstLetter() {
    return nameFullFirstLetter;
  }

  public void setNameFullFirstLetter(String nameFullFirstLetter) {
    this.nameFullFirstLetter = nameFullFirstLetter;
  }

  public String getNameFullLast() {
    return nameFullLast;
  }

  public void setNameFullLast(String nameFullLast) {
    this.nameFullLast = nameFullLast;
  }

}
