package com.raoul.walkfoframe.model;

import com.google.android.gms.maps.model.LatLng;
import com.raoul.walkfoframe.maputtiliy.clustering.ClusterItem;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table HONOREESANDSTAR.
 */
public class HonoreesandStar implements ClusterItem {

  private String honoreeID;
  private String bioThumbnail;
  private String biography;
  private String birthCity;
  private String birthState;
  private String birthCountry;
  private String birthDate;
  private String createdTimeStamp;
  private String deathCity;
  private String deathState;
  private String education;
  private String ethnicity;
  private String inductionDate;
  private String fullName;
  private String nameFullFirst;
  private String nameFullFirstLetter;
  private String nameFullLast;
  private Integer starID;
  private String streetNo;
  private String streetName;
  private String longitude;
  private String latitude;
  private String honoreeFullName;
  private String ceremonyDate;
  private String category;
  private String isfavorite;

  public HonoreesandStar() {}

  public HonoreesandStar(String honoreeID, String bioThumbnail, String biography, String birthCity,
      String birthState, String birthCountry, String birthDate, String createdTimeStamp,
      String deathCity, String deathState, String education, String ethnicity,
      String inductionDate, String fullName, String nameFullFirst, String nameFullFirstLetter,
      String nameFullLast, Integer starID, String streetNo, String streetName, String longitude,
      String latitude, String honoreeFullName, String ceremonyDate, String category,
      String isfavorite) {
    this.honoreeID = honoreeID;
    this.bioThumbnail = bioThumbnail;
    this.biography = biography;
    this.birthCity = birthCity;
    this.birthState = birthState;
    this.birthCountry = birthCountry;
    this.birthDate = birthDate;
    this.createdTimeStamp = createdTimeStamp;
    this.deathCity = deathCity;
    this.deathState = deathState;
    this.education = education;
    this.ethnicity = ethnicity;
    this.inductionDate = inductionDate;
    this.fullName = fullName;
    this.nameFullFirst = nameFullFirst;
    this.nameFullFirstLetter = nameFullFirstLetter;
    this.nameFullLast = nameFullLast;
    this.starID = starID;
    this.streetNo = streetNo;
    this.streetName = streetName;
    this.longitude = longitude;
    this.latitude = latitude;
    this.honoreeFullName = honoreeFullName;
    this.ceremonyDate = ceremonyDate;
    this.category = category;
    this.isfavorite = isfavorite;
  }

  public String getHonoreeID() {
    return honoreeID;
  }

  public void setHonoreeID(String honoreeID) {
    this.honoreeID = honoreeID;
  }

  public String getBioThumbnail() {
    return bioThumbnail;
  }

  public void setBioThumbnail(String bioThumbnail) {
    this.bioThumbnail = bioThumbnail;
  }

  public String getBiography() {
    return biography;
  }

  public void setBiography(String biography) {
    this.biography = biography;
  }

  public String getBirthCity() {
    return birthCity;
  }

  public void setBirthCity(String birthCity) {
    this.birthCity = birthCity;
  }

  public String getBirthState() {
    return birthState;
  }

  public void setBirthState(String birthState) {
    this.birthState = birthState;
  }

  public String getBirthCountry() {
    return birthCountry;
  }

  public void setBirthCountry(String birthCountry) {
    this.birthCountry = birthCountry;
  }

  public String getBirthDate() {
    return birthDate;
  }

  public void setBirthDate(String birthDate) {
    this.birthDate = birthDate;
  }

  public String getCreatedTimeStamp() {
    return createdTimeStamp;
  }

  public void setCreatedTimeStamp(String createdTimeStamp) {
    this.createdTimeStamp = createdTimeStamp;
  }

  public String getDeathCity() {
    return deathCity;
  }

  public void setDeathCity(String deathCity) {
    this.deathCity = deathCity;
  }

  public String getDeathState() {
    return deathState;
  }

  public void setDeathState(String deathState) {
    this.deathState = deathState;
  }

  public String getEducation() {
    return education;
  }

  public void setEducation(String education) {
    this.education = education;
  }

  public String getEthnicity() {
    return ethnicity;
  }

  public void setEthnicity(String ethnicity) {
    this.ethnicity = ethnicity;
  }

  public String getInductionDate() {
    return inductionDate;
  }

  public void setInductionDate(String inductionDate) {
    this.inductionDate = inductionDate;
  }

  public String getFullName() {
    return fullName;
  }

  public void setFullName(String fullName) {
    this.fullName = fullName;
  }

  public String getNameFullFirst() {
    return nameFullFirst;
  }

  public void setNameFullFirst(String nameFullFirst) {
    this.nameFullFirst = nameFullFirst;
  }

  public String getNameFullFirstLetter() {
    return nameFullFirstLetter;
  }

  public void setNameFullFirstLetter(String nameFullFirstLetter) {
    this.nameFullFirstLetter = nameFullFirstLetter;
  }

  public String getNameFullLast() {
    return nameFullLast;
  }

  public void setNameFullLast(String nameFullLast) {
    this.nameFullLast = nameFullLast;
  }

  public Integer getStarID() {
    return starID;
  }

  public void setStarID(Integer starID) {
    this.starID = starID;
  }

  public String getStreetNo() {
    return streetNo;
  }

  public void setStreetNo(String streetNo) {
    this.streetNo = streetNo;
  }

  public String getStreetName() {
    return streetName;
  }

  public void setStreetName(String streetName) {
    this.streetName = streetName;
  }

  public String getLongitude() {
    return longitude;
  }

  public void setLongitude(String longitude) {
    this.longitude = longitude;
  }

  public String getLatitude() {
    return latitude;
  }

  public void setLatitude(String latitude) {
    this.latitude = latitude;
  }

  public String getHonoreeFullName() {
    return honoreeFullName;
  }

  public void setHonoreeFullName(String honoreeFullName) {
    this.honoreeFullName = honoreeFullName;
  }

  public String getCeremonyDate() {
    return ceremonyDate;
  }

  public void setCeremonyDate(String ceremonyDate) {
    this.ceremonyDate = ceremonyDate;
  }

  public String getCategory() {
    return category;
  }

  public void setCategory(String category) {
    this.category = category;
  }

  public String getIsfavorite() {
    return isfavorite;
  }

  public void setIsfavorite(String isfavorite) {
    this.isfavorite = isfavorite;
  }

  @Override
  public LatLng getPosition() {

    try {
      return new LatLng(Double.parseDouble(latitude), Double.parseDouble(longitude));
    } catch (Exception e) {
      e.printStackTrace();
      return new LatLng(0.0, 0.0);
    }
  }

}
