package com.raoul.walkfoframe.model;

import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAttribute;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBHashKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBTable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table WOFCOUPON_CAT.
 */
@DynamoDBTable(tableName = "WOFCouponCat")
public class WOFCouponCat {

    private String CouponCatID;
    private String Category;

    public WOFCouponCat() {
    }

    public WOFCouponCat(String CouponCatID, String Category) {
        this.CouponCatID = CouponCatID;
        this.Category = Category;
    }
    @DynamoDBHashKey(attributeName = "CouponCatID")
    public String getCouponCatID() {
        return CouponCatID;
    }

    public void setCouponCatID(String CouponCatID) {
        this.CouponCatID = CouponCatID;
    }
    @DynamoDBAttribute(attributeName = "Category")
    public String getCategory() {
        return Category;
    }

    public void setCategory(String Category) {
        this.Category = Category;
    }

}
